config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "locations#index"
  # Root path for non-authenticated users
  # root to: "locations#index"


  # Routes for locations
  resources :locations, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    collection do
      post 'locations_action', to: 'locations#locations_action'
      get 'locations/get_info', to: 'locations#get_info'
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  before_save :check_url_change


  def check_url_change
    self.address = LocationsHelper.getInfo(url) if self.url_changed?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:edit, :update, :destroy, :confirm_delete]

  def index
    @locations = Location.all
  end

  def search
    @location = Location.find_by(name: params[:name])
    if @location
      render :confirm_delete
    else
      flash[:alert] = 'Location not found.'
      redirect_to delete_by_name_path
    end
  end

  def new
    @location = Location.new
  end

  def confirm_delete
  end
  def get_info
    locations =  Location.where(id: params[:location_ids])
    info = locations.map do |location|
      { name: location.name, info: LocationsHelper.getInfo(location.address) }
    end
    render info
  end


  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to root_path
    else
      render :new
    end
  end

  def action
    case params[:action_type]
    when 'edit'
      @locations = Location.where(id: params[:location_ids])
      redirect_to edit_location_path(@locations.first) if @locations.any?
    when 'delete'
      Location.where(id: params[:location_ids]).destroy_all
      redirect_to locations_path, notice: 'Selected locations were successfully deleted.'
    else
      redirect_to locations_path, alert: 'Invalid action type.'
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to root_path, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if params[:action_type] == 'delete'
      if params[:location_ids].present?
        Location.where(id: params[:location_ids]).destroy_all
        redirect_to locations_path, notice: 'Locations were successfully deleted.'
      else
        redirect_to locations_path, alert: 'No locations selected for deletion.'
      end
    else
      redirect_to locations_path, alert: 'Invalid action type.'
    end
  end

  def delete_by_name
    @location = Location.find_by(name: params[:name])

    if @location
      @location.destroy
      flash[:notice] = 'Location was successfully deleted.'
    else
      flash[:alert] = 'Location not found.'
    end
    redirect_to locations_path
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :url)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  require 'httparty'
  require 'json'

  def self.getLatLong(url)
    response = HTTParty.get(url, follow_redirects: false)
    location = response.headers['location']
    split_location = location.split('/')
    coords_index = split_location[4] == 'place' ? 6 : 5

    return location.split('/')[coords_index].gsub(/[^0-9,\.]/, '').split(',')[0..1].join(',')
  end

  def self.getInfo(url)
    lat = getLatLong(url)
    api_key = ENV['GOOGLE_MAPS_API_KEY']
    url = "https://maps.googleapis.com/maps/api/geocode/json?latlng=#{lat}&key=#{api_key}"
    response = HTTParty.get(url)
    info = JSON.parse(response.body)

    longName = info['results'][0]["address_components"]
    arr = longName.reverse.map do |info|
      info["long_name"]
    end
    return arr.join(', ') 
  end
end

app/views/locations/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'editStyle.css', media: 'all' %>
</head>
<body>
<%= yield %>
<div class="container">
  <div class="form-container">
    <h1>Edit Location</h1>
    <%= form_with model: @location, local: true do |form| %>
      <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div>
        <%= form.label :url %>
        <%= form.text_field :url %>
      </div>
      <div>
        <%= form.submit 'Update Location' %>
      </div>
    <% end %>
  </div>
</div>
</body>
</html>

app/views/locations/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'styles.css', media: 'all' %>
</head>
<body>
<%= yield %>

<div class="container">
  <%= link_to 'Add Location', new_location_path, class: 'button' %>
</div>

<div id="listBox">
  <button id="toggleButton" onclick="toggleContent()">Locations ↓</button>
  <div id="toggleContent">
    <%= form_with url: locations_action_locations_path, method: :post, local: true, id: 'locationsForm' do %>
      <ul id="locationList">
        <% @locations.each do |location| %>
          <li id="<%= location.id %>">
            <input type="checkbox" name="location_ids[]" value="<%= location.id %>">
            <strong><%= location.name %></strong>
            <a href="<%=location.url%>"><%= location.address %></a>
          </li>
        <% end %>
      </ul>
      <input type="hidden" name="action_type" id="actionType" value="">

      <input type="text" id="fname" name="fname" oninput="search_elements(this.value);"><br><br>

      <button type="button" class="button" onclick="handleAction('edit')">Edit Selected</button>
      <button type="button" class="button" onclick="handleAction('delete')">Delete Selected</button>
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "button" %>
      <% else %>
        <%= button_to "Sign in", new_user_session_path, class: "button"  %>
      <% end %>
    <% end %>
  </div>
</div>
<script>
  const locations = <%= @locations.to_json.html_safe %>
    function toggleContent() {
        const content = document.getElementById('toggleContent');
        content.style.display = content.style.display === 'none' ? 'block' : 'none';
    }

   function search_elements(prompt){
       console.log(prompt)
       var ids_to_keep = search(locations,prompt)

       const list = document.getElementById("locationList").children;
       for(var i=0;i<list.length; i+=1)
       {
          if(ids_to_keep.includes(list[i].id)){
              list[i].style.display ="";
          }
        else list[i].style.display = "none";
       }
   }

    function search(locations, prompt) {
        results = []
        locations.forEach((location) => {
            if (!prompt  || location.name.toLowerCase().includes(prompt.toLowerCase()) ||
                location.address.toLowerCase().includes(prompt.toLowerCase())
            )
            {
                results.push(location.id.toString());
            }
        })
      return results
    }


    function handleAction(action) {
        const form = document.getElementById('locationsForm');
        const checkboxes = form.querySelectorAll('input[name="location_ids[]"]:checked');

        if (checkboxes.length === 0) {
            alert('Please select at least one location.');
            return;
        }

        if (action === 'edit') {
            const selectedIds = Array.from(checkboxes).map(cb => cb.value);
            const firstId = selectedIds[0];
            window.location.href = `/locations/${firstId}/edit`;
        }
    }

</script>
</body>
</html>